### PR TITLE
Add mimetype suggestions to form

### PR DESCRIPTION
**Pull request by bondjimbond**
Adds a list of probably-valid mimetypes, amkes them selectable, instead of an open-ended text box. If there are any in this list that aren't supported, or any that are supported but not in the list, let me know and I'll update the PR.

### CODE REVIEW

**Comment by bondjimbond** [comment]
@rosiel Does the list look right to you?

**Comment by rosiel** [comment]
I don't think there's a static list of acceptable mime types. What if we made it a suggestion list, as part of the description, instead  - so the user could copy-paste?

Also, random aside that might make this irrelevant - have you tried without specifying a mime type? It looks like videojs doesn't require the <mime> element any more. http://docs.videojs.com/tutorial-embeds.html

**Comment by bondjimbond** [comment]
Removing the video/mp4 mimetype works fine, but for your example (application/x-mpegURL), it did not work without the mimetype.

Copy-paste suggestion list would work too, I can edit my branch.

**Comment by bondjimbond** [comment]
Not sure how much HTML markup would be kosher. Want to take a look?

**Comment by rosiel** [comment]
Sweet - thanks! I'll maybe do some html styling... ;) I'm not sure if it's kosher either but i'll take the html out of the t() just to be safe.

**Comment by rosiel** [comment]
If markup is your style... https://github.com/rosiel/islandora_solution_pack_streaming_media/commit/10791f28dbe0ff78e8a281e9475009aa2f92c2eb

**Pull request merged**
